version: '3'

services:
  db:
    image: postgres:11
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  # tracker:
  #   container_name: tracker
  #   image: luhuiguo/fastdfs
  #   command: tracker
  #   network_mode: host
  #   volumes:
  #     - /var/fdfs/tracker:/var/fdfs
  # storage0:
  #   container_name: storage0
  #   image: luhuiguo/fastdfs
  #   command: storage
  #   network_mode: host
  #   environment:
  #     - TRACKER_SERVER=10.1.5.85:22122
  #   volumes:
  #     - /var/fdfs/storage0:/var/fdfs
  # web:
  #   build: .
  #   command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #     - redis
