# Generated by Django 2.2.4 on 2019-08-13 13:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('detail', tinymce.models.HTMLField(blank=True)),
            ],
            options={
                'db_table': 'fs_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='goods')),
                ('stock', models.IntegerField(default=1)),
                ('sales_volume', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Unavailable'), (1, 'Available')], default=1)),
                ('goods', models.ForeignKey(on_delete=True, to='goods.Goods')),
            ],
            options={
                'db_table': 'fs_goods_sku',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('logo', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='type')),
            ],
            options={
                'db_table': 'fs_goods_type',
            },
        ),
        migrations.CreateModel(
            name='IndexPromotionBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='banner')),
                ('index', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'fs_index_promotion',
            },
        ),
        migrations.CreateModel(
            name='IndexTypeGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('display_type', models.SmallIntegerField(choices=[(0, 'title'), (1, 'image')], default=1)),
                ('index', models.SmallIntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=True, to='goods.GoodsSKU')),
                ('type', models.ForeignKey(on_delete=True, to='goods.GoodsType')),
            ],
            options={
                'db_table': 'fs_index_type_goods',
            },
        ),
        migrations.CreateModel(
            name='IndexGoodsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='banner')),
                ('index', models.SmallIntegerField(default=0)),
                ('sku', models.ForeignKey(on_delete=True, to='goods.GoodsSKU')),
            ],
            options={
                'db_table': 'fs_index_banner',
            },
        ),
        migrations.AddField(
            model_name='goodssku',
            name='type',
            field=models.ForeignKey(on_delete=False, to='goods.GoodsType'),
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='goods')),
                ('sku', models.ForeignKey(on_delete=True, to='goods.GoodsSKU')),
            ],
            options={
                'db_table': 'fs_goods_image',
            },
        ),
    ]
